#gcloud runtime: python310
runtime: python310

instance_class: F2

env_variables:
  BUCKET_NAME: "united-park-406303.appspot.com"

entrypoint: gunicorn -b :$PORT app:app

handlers:
- url: /images
  static_dir: static/images

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
